name: manylinux
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    # This is python 3.10 and does not work with cocoindex
    # container: quay.io/pypa/manylinux2014_x86_64
    container: quay.io/pypa/manylinux_2_28_x86_64
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      # Node is needed for actions/cache@v3
      - name: Install Node.js
        run: |
          dnf module install --setopt=install_weak_deps=False -y nodejs:20
          dnf install --setopt=install_weak_deps=False -y zstd
          dnf clean all
      # This must be placed before install node - but if it does not work (cause node is missing)
      # - name: Cache DNF packages
      #   uses: actions/cache@v3
      #   with:
      #     path: /var/cache/dnf
      #     key: ${{ runner.os }}-dnf-${{ hashFiles('**/dnf-install.lock') }}
      #     restore-keys: ${{ runner.os }}-dnf-
      # Cache Rust toolchain + Cargo registry/cache/artifacts
      - name: Cache Rust toolchain and cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          # hangs on | Cache saved with key: Linux-rust-
          key: ${{ runner.os }}-rust-${{ hashFiles('rust/Cargo.lock') }}
      - name: Cache uv binary
        uses: actions/cache@v3
        with:
          path: /usr/bin/uv
          key: ${{ runner.os }}-uv-0.9.3
          restore-keys: ${{ runner.os }}-uv-
      - name: Download uv binary
        run: |
          curl -L -o uv.tar.gz https://github.com/astral-sh/uv/releases/download/0.9.3/uv-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf uv.tar.gz
          chmod +x uv-x86_64-unknown-linux-gnu/uv
          mv uv-x86_64-unknown-linux-gnu/uv /usr/bin
          rm -r uv-x86_64-unknown-linux-gnu
      - name: Verify uv installation
        run: uv --version
      - name: Cache uv pip packages
        uses: actions/cache@v3
        with:
          path: |
            /opt/python/cp311-cp311/lib/python3.11/site-packages
            /opt/python/cp311-cp311/bin
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml', 'rust/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustc --version
          cargo --version
      # pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cpu
      # https://download.pytorch.org/whl/torch/
      # torch-2.9.0+cpu-cp311-cp311-manylinux_2_28_x86_64.whl
      - name: Install maturin
        run: |
          export PATH=/opt/python/cp311-cp311/bin:$PATH
          uv pip install --system torch==2.3.1+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
          uv pip install --system maturin psycopg "psycopg[pool]" pgvector \
            "sentence-transformers" "huggingface_hub[cli]"
          uv pip install --system  -e .
          uv pip install --system  -e ".[test]" ".[mcp-server]" ".[build]"
      # do NOT set compatibility to avoid a nested container with act
      # maturin build --release --compatibility manylinux_2_28
      - name: Build module
        run: |
          export PATH=/opt/python/cp311-cp311/bin:$PATH
          source $HOME/.cargo/env
          maturin build --release
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./rust/target/wheels
