name: Test
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install maturin and test dependencies
        run: |
          pip install maturin pytest
      - name: Build with maturin (develop mode)
        run: maturin develop
      - name: Run tests
        run: pytest tests
